export type Destination = {
  city: string;
  country: string;
  full: string; // "Istanbul, Turkey"
};

const destinations: Destination[] = [
  { city: 'Istanbul', country: 'Turkey', full: 'Istanbul, Turkey' },
  { city: 'Ankara', country: 'Turkey', full: 'Ankara, Turkey' },
  { city: 'Izmir', country: 'Turkey', full: 'Izmir, Turkey' },
  { city: 'Antalya', country: 'Turkey', full: 'Antalya, Turkey' },
  { city: 'Bursa', country: 'Turkey', full: 'Bursa, Turkey' },
  { city: 'Adana', country: 'Turkey', full: 'Adana, Turkey' },
  { city: 'Konya', country: 'Turkey', full: 'Konya, Turkey' },
  { city: 'Gaziantep', country: 'Turkey', full: 'Gaziantep, Turkey' },
  { city: 'Kayseri', country: 'Turkey', full: 'Kayseri, Turkey' },
  { city: 'Mersin', country: 'Turkey', full: 'Mersin, Turkey' },
  { city: 'Eskisehir', country: 'Turkey', full: 'Eskisehir, Turkey' },
  { city: 'Samsun', country: 'Turkey', full: 'Samsun, Turkey' },
  { city: 'Trabzon', country: 'Turkey', full: 'Trabzon, Turkey' },
  { city: 'Diyarbakir', country: 'Turkey', full: 'Diyarbakir, Turkey' },
  { city: 'Sanliurfa', country: 'Turkey', full: 'Sanliurfa, Turkey' },
  { city: 'Denizli', country: 'Turkey', full: 'Denizli, Turkey' },
  { city: 'Malatya', country: 'Turkey', full: 'Malatya, Turkey' },
  { city: 'Erzurum', country: 'Turkey', full: 'Erzurum, Turkey' },
  { city: 'Hatay', country: 'Turkey', full: 'Hatay, Turkey' },
  { city: 'Manisa', country: 'Turkey', full: 'Manisa, Turkey' },
  { city: 'Aydin', country: 'Turkey', full: 'Aydin, Turkey' },
  { city: 'Mugla', country: 'Turkey', full: 'Mugla, Turkey' },
  { city: 'Canakkale', country: 'Turkey', full: 'Canakkale, Turkey' },
  { city: 'Balikesir', country: 'Turkey', full: 'Balikesir, Turkey' },
  { city: 'Kocaeli', country: 'Turkey', full: 'Kocaeli, Turkey' },
  { city: 'Tekirdag', country: 'Turkey', full: 'Tekirdag, Turkey' },
  { city: 'Sakarya', country: 'Turkey', full: 'Sakarya, Turkey' },
  { city: 'Kahramanmaras', country: 'Turkey', full: 'Kahramanmaras, Turkey' },
  { city: 'Elazig', country: 'Turkey', full: 'Elazig, Turkey' },
  { city: 'Van', country: 'Turkey', full: 'Van, Turkey' },
  { city: 'Paris', country: 'France', full: 'Paris, France' },
  { city: 'Rome', country: 'Italy', full: 'Rome, Italy' },
  { city: 'Barcelona', country: 'Spain', full: 'Barcelona, Spain' },
  { city: 'Berlin', country: 'Germany', full: 'Berlin, Germany' },
  { city: 'Amsterdam', country: 'Netherlands', full: 'Amsterdam, Netherlands' },
  { city: 'London', country: 'United Kingdom', full: 'London, United Kingdom' },
  { city: 'Vienna', country: 'Austria', full: 'Vienna, Austria' },
  { city: 'Zurich', country: 'Switzerland', full: 'Zurich, Switzerland' },
  { city: 'Prague', country: 'Czech Republic', full: 'Prague, Czech Republic' },
  { city: 'Lisbon', country: 'Portugal', full: 'Lisbon, Portugal' },
  { city: 'New York', country: 'USA', full: 'New York, USA' },
  { city: 'Los Angeles', country: 'USA', full: 'Los Angeles, USA' },
  { city: 'Chicago', country: 'USA', full: 'Chicago, USA' },
  { city: 'Toronto', country: 'Canada', full: 'Toronto, Canada' },
  { city: 'Vancouver', country: 'Canada', full: 'Vancouver, Canada' },
  { city: 'Tokyo', country: 'Japan', full: 'Tokyo, Japan' },
  { city: 'Kyoto', country: 'Japan', full: 'Kyoto, Japan' },
  { city: 'Seoul', country: 'South Korea', full: 'Seoul, South Korea' },
  { city: 'Bangkok', country: 'Thailand', full: 'Bangkok, Thailand' },
  { city: 'Dubai', country: 'UAE', full: 'Dubai, UAE' },
  { city: 'Doha', country: 'Qatar', full: 'Doha, Qatar' },
  { city: 'Singapore', country: 'Singapore', full: 'Singapore, Singapore' },
  { city: 'Sydney', country: 'Australia', full: 'Sydney, Australia' },
  {
    city: 'Cape Town',
    country: 'South Africa',
    full: 'Cape Town, South Africa',
  },
];

export default destinations;
